# Crear arreglo numpy

In [1]:
# Crear arreglo a partir de la librería numpy
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [5]:
# Crear arreglo tambinen con la librería numpy solo que con un alias np
import numpy as np

arr2 = np.array ([4, 6, 8, 6, 10])

print(arr2)

[ 4  6  8  6 10]


In [6]:
# Versión de numpy
# import numpy as np

print(np.__version__)

1.21.5


In [7]:
# Qu tipo de datos es el arreglo numpy
# import numpy as np

arr = np.array([8, 7, 8, 9, 4])

print(arr)

print(type(arr))

[8 7 8 9 4]
<class 'numpy.ndarray'>


In [37]:
# A partir de una tupla de Python crear un arreglo numpy
# La función type() muestra el tipo de dato, estructura u objeto que se está usando


# import numpy as np

latupla = (4, 5, 6, 7, 6, 8, 9, 8, 7, 6, 5)

arr = np.array(latupla)

print(arr)


print(type(latupla))
print(type(arr))

[4 5 6 7 6 8 9 8 7 6 5]
<class 'tuple'>
<class 'numpy.ndarray'>


In [17]:
# Acceder a elementos del arreglo. Los arreglo numpy comienzan en posición 0, 1, 2,,,,,, n
arr[1]

5

In [23]:
# Arreglos de dos dimensiones, puede tal vez entenderse como un matriz
import numpy as np

matriz = np.array([[1, 2, 3], [4, 5, 6]])

print(matriz)

[[1 2 3]
 [4 5 6]]


In [27]:
# Acceder a elementos del arreglo
print("matriz en renglon 1, columna 1 es:" , matriz[1][1])
print("matriz en renglon 0, columna 2 es:" , matriz[0][2])


matriz en renglon 1, columna 1 es: 5
matriz en renglon 0, columna 2 es: 3


In [34]:
# Arreglo de 3 dimensiones
import numpy as np

arr_tres = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[1, 2, 3], [4, 5, 6]]])

print(arr_tres)

# Accediendo a posiciones específicas

arr_tres[0]
arr_tres[0][1]

arr_tres[1][1][1]

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


5

In [41]:
# Conocer de cuantas dimensiones son los arreglos con el método ndim
print("El arreglo arr es de ", arr.ndim, "D's")
print("El arreglo matriz es de ", matriz.ndim, "D's")
print("El arreglo arr_tres es de ", arr_tres.ndim, "D's")



El arreglo arr es de  1 D's
El arreglo matriz es de  2 D's
El arreglo arr_tres es de  3 D's


In [159]:
# Arreglos con dimensiones no cuadradas,
# Primer fila: [1, 2, 3, 4, 5, 6]
# Segunda fila: [7, 8, 9, 10, 11, 12]
mi_arreglo = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12]])

print(mi_arreglo)

print(mi_arreglo[1][3]) 
# o bien
print(mi_arreglo[1,3])

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
10
10


In [52]:
# Acceder  slice varios elementos de un arreglo con el formao renglon:columna

print("Del renglo 0, los elementos del 3 al 5", [0][3:5])


Del renglo 0, los elementos del 3 al 5 []


In [65]:
# Los arreglos numpy son eficienes para valores numéricos y también pueden almacenar otros tipos de datos

edades = np.array([[1,2,3,6,8],[20, 23, 24, 4, 5]])

print("Las edades", 
      edades)

Las edades [[ 1  2  3  6  8]
 [20 23 24  4  5]]


In [68]:
# Arreglos con otro tipo de datos no  numéricos. sTRING


nombres = np.array(['RUBEN', 'OSCAR', 'PATY'])

print(nombres.dtype)

<U5


In [75]:
# Copiando edades
nums = np.array([6, 7, 8, 4, 5])
nums_cpy = nums.copy()
nums_cpy[0] = 10

print(nums)
print(nums_cpy)

[6 7 8 4 5]
[10  7  8  4  5]


In [77]:
# Modificando las dimensiones del arreglo
print(nums.shape)

(5,)


In [158]:
# Moifiar un arreglo de 1 a dos dimensiones
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("nums ...")
print (nums)
print(nums.shape)


print("nums_cpy")
nums_cpy = nums.copy()

nums_cpy = nums_cpy.reshape(4, 3)

print(nums_cpy)
print(nums_cpy.shape)

print("Renglon 0, Columna1")
print(nums_cpy[0][1])

nums ...
[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
nums_cpy
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
Renglon 0, Columna1
2


In [88]:
# Recorriendo un arreglo numpy

print("nums ...")
for r in nums:
    print (r)
    
print("nums_cpy ...")    
for r in nums_cpy:
    print(r)
        

nums ...
1
2
3
4
5
6
7
8
9
10
11
12
nums_cpy ...
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [89]:
# Concatenar arreglos
nums1 = np.array([4, 5, 3])

nums2 = np.array([6, 7, 8])

arr = np.concatenate((nums1, nums2))

print(arr)

[4 5 3 6 7 8]


In [110]:
# Cortes de un arreglo con array_split(arreglo, cortes)

cortes = 5
arr = np.array([1, 2, 3, 4, 5, 6, 5, 6, 4, 5, 6, 7, 6, 9])


print(arr)
print(arr.shape)


print("Haciendo cortes")
newarr = np.array_split(arr, cortes) 

print(newarr)

print(newarr[0])
print(newarr[1])

# Longitud del arreglo
# print(newarr.shape)


num_cortes = len(newarr)
print("Cortes del nuevo arreglo: ", num_cortes)
print("Iterando ... recorriendo por medio de un bucle o ciclo for ")
for c in newarr:
    print(c)

[1 2 3 4 5 6 5 6 4 5 6 7 6 9]
(14,)
Haciendo cortes
[array([1, 2, 3]), array([4, 5, 6]), array([5, 6, 4]), array([5, 6, 7]), array([6, 9])]
[1 2 3]
[4 5 6]
Cortes del nuevo arreglo:  5
Iterando ... recorriendo por medio de un bucle o ciclo for 
[1 2 3]
[4 5 6]
[5 6 4]
[5 6 7]
[6 9]


In [122]:
# Encontrar valores devolviendo el índice de un arreglo
nums = np.array([3, 4, 5, 6, 5, 4, 5, 6, 5, 4, 3])
print(nums)

posicion = np.where(nums == 4)
print("La(s) posiciones en donde hay 4 son: ", posicion)

for p in posicion:
    print(p) 






[3 4 5 6 5 4 5 6 5 4 3]
La(s) posiciones en donde hay 4 son:  (array([1, 5, 9], dtype=int64),)
[1 5 9]


In [137]:
# Ordenar un arreglo numérico ascendente y descendente
arr = np.array([3, 2, 0, 7, 1, 4, 5, 3, 6, 7, 8, 7, 6, 5, 4, 5, 6, 1])

print(np.sort(arr))
print(np.sort(arr)[::-1])

[0 1 1 2 3 3 4 4 5 5 5 6 6 6 7 7 7 8]
[8 7 7 7 6 6 6 5 5 5 4 4 3 3 2 1 1 0]


In [140]:
# Filtrar con valore booleandos solo lo eleentos que se le indica True
arr = np.array([41, 42, 43, 44, 46, 54, 56])

x = [True, False, True, False, True, True, False]

newarr = arr[x]

print(newarr)

[41 43 46 54]


Dado un arreglo de números aleatorios de forma (5, 5) con valores enteros entre 18 y 65, encuentra el número más grande y más pequeño de cada renglón del arreglo y reemplaza todos los demás números del arreglo con cero.

In [168]:
# Encontrar el número más grande y más pequeño del arreglo
# Crear arreglo aleatorio de 5x5

import numpy as np

numeros = np.random.randint(18, 65, size=25)
print(numeros)


matriz = numeros.reshape(5,5)
print(matriz)

# Copia de la matriz
matriz_cpy = matriz.copy()


# Iterar registros y columnas de la matriz
for r in range(0, 5):
    for c in range(0, 5):
        print(matriz[r,c])
        
for n in matriz:
    print (n)
    
print("Los máximos de cada renglón")   

# Crear una copia de la matriz original
matriz_cpy = matriz.copy()

# Para cada renglón, encontrar el valor máximo y reemplazar los otros valores por 0
for r in range(5):
    maximo = np.max(matriz[r])
    minimo = np.min(matriz[r])
    # Iterar sobre cada elemento de la matriz copia
    for c in range(5):
        if matriz_cpy[r, c] != maximo and matriz_cpy[r, c] != minimo:
            matriz_cpy[r, c] = 0  # Asignar un valor de 0 a los elementos que no sean el máximo o mínimo del renglón
    
print("Matriz original")
print(matriz)
    
print("Matriz modificada:")
print(matriz_cpy)



[18 26 44 33 58 61 64 28 47 27 34 43 46 28 63 57 27 18 50 39 48 61 50 49
 47]
[[18 26 44 33 58]
 [61 64 28 47 27]
 [34 43 46 28 63]
 [57 27 18 50 39]
 [48 61 50 49 47]]
18
26
44
33
58
61
64
28
47
27
34
43
46
28
63
57
27
18
50
39
48
61
50
49
47
[18 26 44 33 58]
[61 64 28 47 27]
[34 43 46 28 63]
[57 27 18 50 39]
[48 61 50 49 47]
Los máximos de cada renglón
Matriz original
[[18 26 44 33 58]
 [61 64 28 47 27]
 [34 43 46 28 63]
 [57 27 18 50 39]
 [48 61 50 49 47]]
Matriz modificada:
[[18  0  0  0 58]
 [ 0 64  0  0 27]
 [ 0  0  0 28 63]
 [57  0 18  0  0]
 [ 0 61  0  0 47]]
